services:
  npm:
    container_name: ai-s1-it-npm
    image: node:22.14-alpine
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5173:5173"
    working_dir: /app
    entrypoint: [ "sh", "-c" ]
    command: ["tail -f /dev/null"]